services:
    seven_manager_admin.admin.pages:
        class: SevenManager\AdminBundle\Admin\SimplePageAdmin
        arguments:
            - ''
            - SevenManager\BasicCmsBundle\Document\SimplePage
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Simple Content', label: 'Pages' }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager_admin.admin.posts:
        class: SevenManager\AdminBundle\Admin\SimplePostAdmin
        arguments:
            - ''
            - SevenManager\BasicCmsBundle\Document\SimplePost
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Simple Content', label: 'Posts' }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]