services:

    # Seven Manager - Call Content Bundle
    seven_manager_admin.admin.content.homepage:
        class: SevenManager\AdminBundle\Admin\HomepageAdmin
        arguments:
            - ''
            - SevenManager\ContentBundle\Document\Homepage
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Content', label: seven_manager.shared.labels.homepage }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager_admin.admin.content.node:
        class: SevenManager\AdminBundle\Admin\NodeAdmin
        arguments:
            - ''
            - SevenManager\ContentBundle\Document\Node
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Content', label: seven_manager.shared.labels.node }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager_admin.admin.content.page:
        class: SevenManager\AdminBundle\Admin\PageAdmin
        arguments:
            - ''
            - SevenManager\ContentBundle\Document\Page
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Content', label: seven_manager.shared.labels.page }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager_admin.admin.content.post:
        class: SevenManager\AdminBundle\Admin\PostAdmin
        arguments:
            - ''
            - SevenManager\ContentBundle\Document\Post
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Content', label: seven_manager.shared.labels.post }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager_admin.admin.content.article:
        class: SevenManager\AdminBundle\Admin\ArticleAdmin
        arguments:
            - ''
            - SevenManager\ContentBundle\Document\Article
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Content', label: seven_manager.shared.labels.article }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    seven_manager_admin.admin.content.gallery:
        class: SevenManager\AdminBundle\Admin\GalleryAdmin
        arguments:
            - ''
            - SevenManager\ContentBundle\Document\Gallery
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Content', label: seven_manager.shared.labels.gallery }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]


    seven_manager_admin.admin.content.form:
        class: SevenManager\AdminBundle\Admin\FormAdmin
        arguments:
            - ''
            - SevenManager\ContentBundle\Document\Form
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Seven Manager - Content', label: seven_manager.shared.labels.form }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]