SevenManager\ContentBundle\Document\Homepage:
    #uri_schema:/{locale}/seven-manager/homepage/{date}/{title}
    uri_schema: /{locale}/seven-manager/homepage/{title}
    token_providers:
        #date: [content_datetime, { method: getDate }] // Call methods and add to variables used by uri_schema
        title: [content_method, { method: getTitle }]
        locale: [content_method, { method: getLocale }]

SevenManager\ContentBundle\Document\Node:
    uri_schema: /{locale}/seven-manager/node/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

SevenManager\ContentBundle\Document\Page:
    uri_schema: /{locale}/seven-manager/page/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

SevenManager\ContentBundle\Document\Post:
    uri_schema: /{locale}/seven-manager/post/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

SevenManager\ContentBundle\Document\Article:
    uri_schema: /{locale}/seven-manager/article/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

SevenManager\ContentBundle\Document\Gallery:
    uri_schema: /{locale}/seven-manager/gallery/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

SevenManager\ContentBundle\Document\Form:
    uri_schema: /{locale}/seven-manager/form/{title}
    token_providers:
        title: [content_method, { method: getTitle }]
