SevenManager\BasicCmsBundle\Document\SimplePage:
    uri_schema: /page/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

SevenManager\BasicCmsBundle\Document\SimplePost:
    uri_schema: /post/{date}/{title}
    token_providers:
        date: [content_datetime, { method: getDate }]
        title: [content_method, { method: getTitle }]