services:
    seven_manager_basic_cms.basic_cms.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - Seven Manager - Simple Initializer
            - ["/cms/pages", "/cms/posts", "/cms/routes", "/seven-manager-basic/routes", "/seven-manager-basic/posts", "/seven-manager-basic/pages"]
        tags:
            - { name: doctrine_phpcr.initializer }