parameters:
    phpcr_backend:
        logging: true
        profiling: true
        type: doctrinedbal
        connection: default
        parameters:
            jackalope.check_login_on_server: false
    phpcr_workspace: default
    phpcr_user: admin
    phpcr_pass: admin
