# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_app:
    resource: "@AppBundle/Controller"
    type: annotation

home_redirect:
    pattern: /
    defaults:
        _controller: lunetics_locale.switcher_controller:switchAction
        route: /cms/routes/%locale%
        statusCode: 301
        useReferrer: false

admin_wo_locale:
    pattern: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin_dashboard_wo_locale:
    pattern: /admin/dashboard
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin_dashboard:
    pattern: /{_locale}/admin/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /{_locale}/admin

sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: @FOSJsRoutingBundle/Resources/config/routing/routing.xml

cmf_tree:
    resource: .
    type: 'cmf_tree'

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

liip_search:
    resource: "@CmfSearchBundle/Resources/config/routing/phpcr/search.xml"

block_cache:
    resource: "@CmfBlockBundle/Resources/config/routing/cache.xml"
    prefix: /

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

#sonata_page_exceptions:
#    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'
#    prefix: /

#sonata_page_cache:
#    resource: '@SonataPageBundle/Resources/config/routing/cache.xml'
#    prefix: /

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media


# Seven Manager - Routes
seven_manager_content:
    resource: "@SevenManagerContentBundle/Resources/config/routing.yml"
    prefix:   /

seven_manager_basic_cms:
    resource: "@SevenManagerBasicCmsBundle/Resources/config/routing.yml"
    prefix:   /

seven_manager_pages:
    resource: "@SevenManagerPagesBundle/Resources/config/routing.yml"
    prefix:   /

_seven_manager_admin:
    resource: "@SevenManagerAdminBundle/Controller"
    type: annotation