SevenManager\FixturesBundle\Document\SimplePage:
    uri_schema: /seven-manager/fixtures/simple-page/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

SevenManager\FixturesBundle\Document\SimplePost:
    uri_schema: /seven-manager/fixtures/simple-post/{date}/{title}
    token_providers:
        date: [content_datetime, { method: getDate }]
        title: [content_method, { method: getTitle }]